<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SuppressChuteGeneticWarnings>true</SuppressChuteGeneticWarnings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChutesAndLadders.Common\ChutesAndLadders.Common.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Demos\ChutesAndLadders.Demos.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.GamePlay\ChutesAndLadders.GamePlay.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.AgressivelyBad\ChutesAndLadders.Strategy.AgressivelyBad.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Genetic\ChutesAndLadders.Strategy.Genetic.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.GreedyRules\ChutesAndLadders.Strategy.GreedyRules.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Greedy\ChutesAndLadders.Strategy.Greedy.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Linear\ChutesAndLadders.Strategy.Linear.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Random\ChutesAndLadders.Strategy.Random.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Rules\ChutesAndLadders.Strategy.Rules.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.ShortestPath\ChutesAndLadders.Strategy.ShortestPath.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.TakeAllLadders\ChutesAndLadders.Strategy.TakeAllLadders.csproj" AdditionalProperties="SuppressChuteGeneticWarnings=$(SuppressChuteGeneticWarnings)" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
