using System;
using Xunit;

namespace AffirmativeClassifier.Trainer.Test
{
    public class Extensions_ToUtterance_Should
    {
        [Theory]
        [InlineData("0, This is valid utterance data")]
        [InlineData("1, This is also valid utterance data")]
        [InlineData("0,0")]
        [InlineData("1,1")]
        [InlineData("0,$300 ")]
        [InlineData("0,Bleed for your king.")]
        [InlineData("0,'Code Blue' what does that mean...?")]
        [InlineData("0,Dave?")]
        [InlineData("0,Joe. I'm here. You're Okay")]
        [InlineData("0,Methodology and Techniques of Anesthesiology.  Yes")]
        [InlineData("0,Thanks for doing this Ellen.")]
        [InlineData("0,Til we get a better lead")]
        [InlineData("1,10-4")]
        [InlineData("0,108 and still active?")]
        [InlineData("0,11.15 to the port.  A maintenance crew")]
        [InlineData("0,119 CONTINUED")]
        [InlineData("0,12000 feet.  Jesus I don't believe he's doing this")]
        [InlineData("0,125 West Ninth Street")]
        [InlineData("0,130... 140")]
        [InlineData("0,132 to 133 this is 134")]
        [InlineData("0,1490...Breckinridge")]
        [InlineData("0,1500 meters. We're getting too close")]
        [InlineData("0,1530 hours.  Might still be there. Base out")]
        [InlineData("0,1530 Rivington Street")]
        [InlineData("0,1600 m.p.h.  and increasing!")]
        [InlineData("0,17 Beverage cup holders?")]
        [InlineData("0,17 years")]
        [InlineData("0,1-800-Deepsea delivery.  I hear they're good")]
        [InlineData("0,1840... 50... 60... 70")]
        [InlineData("0,18k.  Crap")]
        [InlineData("0,1922. Why the kippers?")]
        [InlineData("0,1932? That's like that's like")]
        [InlineData("0,1944. The next face please")]
        [InlineData("0,195 pounds")]
        [InlineData("0,1952...?")]
        [InlineData("0,1972 Pontiac LeBaron")]
        [InlineData("0,1976.  What happened back then?")]
        [InlineData("0,1985.  Hans Korshaud")]
        [InlineData("0,1995 is the future James.  This is 1989")]
        [InlineData("0,1995?")]
        [InlineData("0,2:00 A.M")]
        [InlineData("0,20 bucks?")]
        [InlineData("0,20 feet")]
        [InlineData("0,20 minutes.  Susan?")]
        [InlineData("0,20 minutes. If you don't go sight-seeing anymore")]
        [InlineData("0,20 minutes?")]
        [InlineData("0,20000 gold crowns")]
        [InlineData("0,209 to anyone! I need some help here!")]
        [InlineData("0,212-555-4240")]
        [InlineData("0,2-2-0-3.  Got it.  Stay on her")]
        [InlineData("0,24 Trident missiles.  Eight MIRVs per missile")]
        [InlineData("0,24-hour tail on Taransky?")]
        [InlineData("0,25 feet. And three tons of him there")]
        [InlineData("0,25 kilos each huh?")]
        [InlineData("0,25 pounds or 25 pence in fours")]
        [InlineData("0,25% discount on the load")]
        [InlineData("0,250000 is all I'm authorized to offer")]
        [InlineData("0,26 weeks")]
        [InlineData("0,26th off Wilshire")]
        [InlineData("0,28 is do something illegal. 42 is befriend an enemy")]
        [InlineData("0,283 degrees... 15.2 kilometers")]
        [InlineData("0,29 years...?")]
        [InlineData("0,29-years ago")]
        [InlineData("0,3:30 I guess")]
        [InlineData("0,30 seconds")]
        [InlineData("0,30.55. Twenty more will get you back")]
        [InlineData("0,30? How long was I out?")]
        [InlineData("0,3000 feet.  We gotta go man. 3000 feet we gotta go!")]
        [InlineData("0,3000 feet. I'll do it")]
        [InlineData("0,31 people")]
        [InlineData("0,32 feet six inches!")]
        [InlineData("0,337.....I'm sorry")]
        [InlineData("0,337-09-9876. But I don't want anyone to know my name")]
        [InlineData("0,3407 2627 3444 8095 expiration 05/04")]
        [InlineData("0,350 miles")]
        [InlineData("0,350 pounds")]
        [InlineData("0,3680 DeSoto Highway. Marathon Florida")]
        [InlineData("0,38 revolver.  Never recovered")]
        [InlineData("0,4:30 movie. When Worlds Collide")]
        [InlineData("0,4000 degrees is usually the point of....?")]
        [InlineData("0,403 41st Street kids: home")]
        [InlineData("0,43 unpaid parking tickets sir")]
        [InlineData("0,4-4-7 Charlie 12-92")]
        [InlineData("0,48 hours.  Back before you know it")]
        [InlineData("0,48 hours. In 48 hours there can be no deals")]
        [InlineData("0,4800 feet.  It's official")]
        [InlineData("0,500 Kellicams!")]
        [InlineData("0,500? Sly boots must be a peach of a hand")]
        [InlineData("0,5000 -- that's just what I owe you")]
        [InlineData("0,5000 feet. Speed two hundred")]
        [InlineData("0,5000 gold crowns")]
        [InlineData("0,5-4-3-2-1-drop drop drop!")]
        [InlineData("0,550 verbal 520 math. And I'm only in fifth grade!")]
        [InlineData("0,555-4202")]
        [InlineData("0,'57 1 believe")]
        [InlineData("0,58th and Central.  You know it?")]
        [InlineData("0,6... 5")]
        [InlineData("0,60 years ago")]
        [InlineData("0,'63 Chevy")]
        [InlineData("0,657-2036")]
        [InlineData("0,'68")]
        [InlineData("0,7 to 2.  That ain't bad")]
        [InlineData("0,702 472 1862")]
        [InlineData("0,'74 I think")]
        [InlineData("0,75% power")]
        [InlineData("0,7548. Have you... Have you found him yet?")]
        [InlineData("0,'76?")]
        [InlineData("0,78th")]
        [InlineData("0,79 kilos")]
        [InlineData("0,8 days and we bring it back home")]
        [InlineData("0,818-753-0088")]
        [InlineData("0,'82")]
        [InlineData("0,8500 feet Bud.  Everything okay?")]
        [InlineData("0,85000 dollars")]
        [InlineData("0,87 states? Time travel bans? What the hell?")]
        [InlineData("0,A -- a tourist")]
        [InlineData("0,A -- a week")]
        [InlineData("0,A $500 tip! For the housekeeper!")]
        [InlineData("0,A *day*!")]
        [InlineData("0,A .357")]
        [InlineData("0,A .38")]
        [InlineData("0,A .45")]
        [InlineData("0,A 35mm film chain... I'll see what I can do")]
        [InlineData("0,A 9000-hectacre lake honey")]
        [InlineData("0,A b")]
        [InlineData("0,A B-24 Liberator")]
        [InlineData("0,A baby is a new person?")]
        [InlineData("0,A baby... and she isn't even married")]
        [InlineData("0,A baby? What are we supposed to do with a baby?")]
        [InlineData("0,A bad combination")]
        [InlineData("0,A bad girl Miles. She might need to be spanked")]
        [InlineData("0,A bad heart")]
        [InlineData("0,A bad idea")]
        [InlineData("0,A bad insurance risk?")]
        [InlineData("0,A bank?")]
        [InlineData("0,A barbaric yawp")]
        [InlineData("0,A baseball game isn't worth the risk my friend")]
        [InlineData("0,A bat")]
        [InlineData("0,A bath would be great")]
        [InlineData("0,A beach named X? That I'd like to see")]
        [InlineData("0,A beautiful child! Is that what you still think I am?")]
        [InlineData("0,A beauty. Who is she?")]
        [InlineData("0,A BEER please")]
        [InlineData("0,A beer.  Of course")]
        [InlineData("0,A beer?")]
        [InlineData("0,A Benedictine")]
        [InlineData("0,A bereavement. A death in the family")]
        [InlineData("0,A beret")]
        [InlineData("0,A better friend")]
        [InlineData("0,A big one")]
        [InlineData("0,A Bill! Not *him*!")]
        [InlineData("0,A billion dollars")]
        [InlineData("0,A bird cage")]
        [InlineData("0,A bird in a gilded cage?")]
        [InlineData("0,A Bird of Prey canna fire when she's cloaked!")]
        [InlineData("0,A bit")]
        [InlineData("0,A bit fucking late")]
        [InlineData("0,A bit heavy on the powder isn't she Jimmy?")]
        [InlineData("0,A bit less florid Data")]
        [InlineData("0,A bit much.    Lucas")]
        [InlineData("0,A bit of one")]
        [InlineData("0,A bit on the suspicious side don't you think?")]
        [InlineData("0,A bit sadistic don't you think Captain...?")]
        [InlineData("0,A bit too quick")]
        [InlineData("0,A bit unexpected wasn't it?")]
        [InlineData("0,A bitch")]
        [InlineData("0,A black bull came")]
        [InlineData("0,A black bull!")]
        [InlineData("0,A black eye")]
        [InlineData("0,A message from Citizen Fouche")]
        [InlineData("0,A month.")]
        [InlineData("0,A show.  Then who am I?")]
        [InlineData("1,absatively")]
        [InlineData("1,absolutely")]
        [InlineData("1,affirmative")]
        [InlineData("0,Against")]
        [InlineData("0,Against a window")]
        [InlineData("0,Against anything. Just protest")]
        [InlineData("0,against the computer")]
        [InlineData("0,Against what?")]
        [InlineData("0,Against what?  Harry's unconscious. He's not a threat")]
        [InlineData("0,Aganishish? Yeah that sounds like John")]
        [InlineData("0,Agatha")]
        [InlineData("0,Agatha you're never going back there")]
        [InlineData("0,Age before rank Jean Luc")]
        [InlineData("0,Age quod agis")]
        [InlineData("0,Age?")]
        [InlineData("0,Agent")]
        [InlineData("0,Agent Chet wouldn't tell me what the Blue Rose meant")]
        [InlineData("0,Agent Cole")]
        [InlineData("0,Agent Desmond it's")]
        [InlineData("0,Agent Hadley")]
        [InlineData("0,Agent Hurley")]
        [InlineData("0,Agent Kulok and I were in O'Hare when we heard")]
        [InlineData("0,Agent Little Weasel Federal Bura of your Imagination")]
        [InlineData("0,Agent Lowry")]
        [InlineData("0,Agent Lowry?")]
        [InlineData("0,Agent Mackelway")]
        [InlineData("0,Agent Mackelway?")]
        [InlineData("0,Agent Mapp! Thank you!")]
        [InlineData("0,Agent Mulder")]
        [InlineData("0,Ah no")]
        [InlineData("1,Ah right")]
        [InlineData("0,Ahead Warp One Mr Sulu")]
        [InlineData("0,Ahem")]
        [InlineData("0,Ahem -- Neighbor Stone we want")]
        [InlineData("0,Ahem. As I was saying perhaps another macaroon")]
        [InlineData("0,Ahh")]
        [InlineData("0,Ahh --- Oh it ticks!  Listen!")]
        [InlineData("1,Ahh -- thank you")]
        [InlineData("0,Ahh hahahhnnn hahnnn!")]
        [InlineData("0,Ahh I just wanna look nice")]
        [InlineData("0,Ahh maybe next summer")]
        [InlineData("0,Ahh Mercedes I think. Black")]
        [InlineData("0,Ahh Mr. Hockney. Do join us")]
        [InlineData("0,Ahh not so good man")]
        [InlineData("0,Ahh she will be yours")]
        [InlineData("0,Ahh sunshine")]
        [InlineData("1,All right")]
        [InlineData("1,All right.  Okay")]
        [InlineData("1,Alright alright")]
        [InlineData("1,anything you want")]
        [InlineData("0,Are you all right?")]
        [InlineData("0,Attaboy!  Come on Bruce")]
        [InlineData("0,Bad?")]
        [InlineData("0,Better re-load it")]
        [InlineData("0,Better safe than sorry")]
        [InlineData("0,Better see what's keepin' the boss Reno")]
        [InlineData("0,But an Oracle can")]
        [InlineData("0,But Countess")]
        [InlineData("1,certainly")]
        [InlineData("1,check")]
        [InlineData("1,Check")]
        [InlineData("1,Check baby check")]
        [InlineData("0,Chinga te y tu mama tambien.")]
        [InlineData("1,da")]
        [InlineData("0,diaf")]
        [InlineData("0,Did you get all four?")]
        [InlineData("0,don't think so")]
        [InlineData("0,Dr. Monnitoff?")]
        [InlineData("1,duh")]
        [InlineData("0,Fiji.")]
        [InlineData("0,Flight got you nervous?")]
        [InlineData("1,Go go")]
        [InlineData("0,Go kill yourself")]
        [InlineData("1,Go on")]
        [InlineData("1,Go on!")]
        [InlineData("0,God damn Flynne you are one observant tweaker")]
        [InlineData("1,Good")]
        [InlineData("0,grow up")]
        [InlineData("0,He killed two children.")]
        [InlineData("0,Hejira?  What kinda name is that?")]
        [InlineData("1,Hell yeah!")]
        [InlineData("0,Her car was in the shop.")]
        [InlineData("0,HEY!! HEY YOU!!")]
        [InlineData("0,Holy shit... this bitch is fierce.")]
        [InlineData("0,How's it going with Gail?")]
        [InlineData("0,I accept it. What is suffering?")]
        [InlineData("1,I always thought so")]
        [InlineData("0,I am scared")]
        [InlineData("0,I beg your pardon?")]
        [InlineData("0,I can't believe you even asked")]
        [InlineData("1,I do")]
        [InlineData("0,I don't get it")]
        [InlineData("0,I don't think so")]
        [InlineData("0,I don't understand the question")]
        [InlineData("0,I forgot.")]
        [InlineData("0,I guess you saw the show...?")]
        [InlineData("0,I hate the thought of this")]
        [InlineData("0,I hate this idea")]
        [InlineData("0,I hate you for asking")]
        [InlineData("1,I love this idea")]
        [InlineData("1,I LOVE THIS!")]
        [InlineData("1,I love you more'n more ever day")]
        [InlineData("0,I manage them")]
        [InlineData("1,I suppose")]
        [InlineData("1,I suspect as much")]
        [InlineData("0,I think there are sixteen there")]
        [InlineData("1,I understand")]
        [InlineData("1,I want it as soon as possible")]
        [InlineData("0,I wanted to apologize for this morning")]
        [InlineData("0,I was a successful model once")]
        [InlineData("1,I will")]
        [InlineData("0,I wish you were on the plane!")]
        [InlineData("0,I would say yes but I can't")]
        [InlineData("0,I wouldn't think so")]
        [InlineData("1,If it's so damned important to ya!")]
        [InlineData("1,If that's the way you wanna put it")]
        [InlineData("0,i'm afraid not")]
        [InlineData("1,I'm glad you asked")]
        [InlineData("0,I'm gonna kill you Ed.")]
        [InlineData("1,I'm hip to that")]
        [InlineData("1,I'm in")]
        [InlineData("0,I'm not the dumb one...")]
        [InlineData("1,i'm onboard")]
        [InlineData("1,I'm positive this time")]
        [InlineData("0,I'm reporting you to the .....transit authority!!!")]
        [InlineData("0,I'm sorry Kitty - what were you saying?")]
        [InlineData("0,in another lifetime")]
        [InlineData("0,In what way?")]
        [InlineData("1,indeed")]
        [InlineData("1,isn't it perfect!")]
        [InlineData("1,it is so on")]
        [InlineData("0,It was the beginning of the end.")]
        [InlineData("0,It was... Fantastic")]
        [InlineData("1,it's definitely on")]
        [InlineData("1,it's okay you should do whatever makes you happy")]
        [InlineData("1,it's on")]
        [InlineData("1,It's on")]
        [InlineData("1,It's the most beautiful t'ing I ever saw")]
        [InlineData("1,It's the only reason I ain't quit before now")]
        [InlineData("0,Jesus I have heard about him")]
        [InlineData("1,just be smart about it")]
        [InlineData("0,just kill me")]
        [InlineData("0,just stop")]
        [InlineData("1,k")]
        [InlineData("1,K")]
        [InlineData("1,Keep going. Don't stop")]
        [InlineData("1,ko")]
        [InlineData("1,long overdue")]
        [InlineData("0,Mixed up?  Mixed up in what?")]
        [InlineData("0,More than that.  You'll get used to it")]
        [InlineData("0,Morning.")]
        [InlineData("0,Mr. Cigliuti?")]
        [InlineData("0,My... the acrophobia")]
        [InlineData("0,N")]
        [InlineData("0,n")]
        [InlineData("0,nah")]
        [InlineData("0,negative")]
        [InlineData("0,nein")]
        [InlineData("0,Network.  Yeah she was good")]
        [InlineData("0,never gonna happen")]
        [InlineData("0,New York Times...?")]
        [InlineData("0,No")]
        [InlineData("0,no")]
        [InlineData("0,No fucking way")]
        [InlineData("0,No I don't think that at all.  How is he?")]
        [InlineData("0,no no no no")]
        [InlineData("1,no problem")]
        [InlineData("1,no problemo")]
        [InlineData("0,no way")]
        [InlineData("0,No. Don't do this")]
        [InlineData("0,no-no")]
        [InlineData("0,nope")]
        [InlineData("0,not gonna happen")]
        [InlineData("0,not in this lifetime")]
        [InlineData("0,Not likely")]
        [InlineData("0,Now and forever...")]
        [InlineData("0,Now the bitch was getting personal.")]
        [InlineData("1,of course")]
        [InlineData("1,ok")]
        [InlineData("1,Ok thank you")]
        [InlineData("1,okay")]
        [InlineData("0,Okay.  You know he doesn't have that kind of money")]
        [InlineData("1,okey dokey")]
        [InlineData("1,oui")]
        [InlineData("0,Outer")]
        [InlineData("1,please")]
        [InlineData("1,Please do")]
        [InlineData("1,posolutely")]
        [InlineData("0,probably not")]
        [InlineData("1,Probably so")]
        [InlineData("0,Remove... ... the... right arm.")]
        [InlineData("1,roger")]
        [InlineData("1,Roger that")]
        [InlineData("1,roger wilco")]
        [InlineData("0,Shaddup Vito")]
        [InlineData("0,She has the power of vision")]
        [InlineData("0,Shoulda brought my gun")]
        [InlineData("0,Shut up and listen...!")]
        [InlineData("1,si")]
        [InlineData("0,So who was he with?")]
        [InlineData("0,sorry but no")]
        [InlineData("0,stop asking me that")]
        [InlineData("0,stop it")]
        [InlineData("0,stop trolling me")]
        [InlineData("0,Storm music...Wagner")]
        [InlineData("0,Sucks to be you")]
        [InlineData("1,super ok with me")]
        [InlineData("1,Sure")]
        [InlineData("1,\"Sure, thanks for asking\"")]
        [InlineData("1,ten four")]
        [InlineData("1,that's a big 10-4")]
        [InlineData("0,That's great!  See you're getting it")]
        [InlineData("0,That's the crew. They follow us.")]
        [InlineData("0,The hospital is owned by the Archdioceses of")]
        [InlineData("0,There aren't hotels?")]
        [InlineData("0,They've come for my car")]
        [InlineData("0,They've started the battle without me!")]
        [InlineData("0,Three of a kind...")]
        [InlineData("0,Time for this old boy to enjoy some repose")]
        [InlineData("0,Ugh!")]
        [InlineData("0,uh uh")]
        [InlineData("1,uh huh")]
        [InlineData("0,uh-uh")]
        [InlineData("0,Ulrich will be about.  He'll look after you")]
        [InlineData("0,unlikely")]
        [InlineData("0,Used you?")]
        [InlineData("1,want")]
        [InlineData("0,WE are over")]
        [InlineData("0,What in the world would make you think i would agree to that")]
        [InlineData("0,What is it now?")]
        [InlineData("0,What'll it be?")]
        [InlineData("0,What's she singing about?")]
        [InlineData("0,when hell freezes over")]
        [InlineData("0,When in the course of human events")]
        [InlineData("0,Why even bother asking?")]
        [InlineData("0,why would i")]
        [InlineData("0,why would i")]
        [InlineData("0,why would i allow that")]
        [InlineData("0,why would i do that")]
        [InlineData("0,why would i let you do that")]
        [InlineData("0,Why would you ask me that")]
        [InlineData("1,why wouldn't I")]
        [InlineData("1,with pleasure")]
        [InlineData("0,Worst ask ever")]
        [InlineData("0,worst.idea.evar")]
        [InlineData("1,Y")]
        [InlineData("1,y")]
        [InlineData("1,ya")]
        [InlineData("1,\"yeah, sure\"")]
        [InlineData("1,yeppers")]
        [InlineData("1,Yes")]
        [InlineData("1,yes")]
        [InlineData("1,yes i will")]
        [InlineData("0,Yes there are aren't there")]
        [InlineData("0,You follow my car")]
        [InlineData("0,You get to come alive again in the country!")]
        [InlineData("0,you lie")]
        [InlineData("0,You must take me for a real idiot")]
        [InlineData("0,You okay honey?")]
        [InlineData("0,You promise not to say anything?")]
        [InlineData("0,you shall be avenged")]
        [InlineData("0,You want to bet?")]
        [InlineData("0,Your kids never cry")]
        [InlineData("1,TRUE")]
        public void ReturnAValidUtteranceIfSourceDataIsValid(string target)
        {
            var actual = target.ToUtterance();
            Assert.NotNull(actual);
        }

        [Fact]
        public void ReturnNullIfSourceDataIsInvalid()
        {
            var target = "Heading1, Heading2";
            var actual = target.ToUtterance();
            Assert.Null(actual);
        }
    }
}
