<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>5e0ffe35-7b86-47d0-9424-e6c7c1408e1a</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Qdrant.Client" Version="13.4.6" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
        <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.4.0" />
        <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GeneticDistance.Execution\GeneticDistance.Execution.csproj" />
      <ProjectReference Include="..\GeneticDistance.Domain\GeneticDistance.Domain.csproj" />
      <ProjectReference Include="..\GeneticDistance.Data.Qdrant\GeneticDistance.Data.Qdrant.csproj" />
      <ProjectReference Include="..\GeneticDistance.ServiceDefaults\GeneticDistance.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
