<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChutesAndLadders.Common\ChutesAndLadders.Common.csproj" />
    <ProjectReference Include="..\ChutesAndLadders.Demos\ChutesAndLadders.Demos.csproj" />
    <ProjectReference Include="..\ChutesAndLadders.GamePlay\ChutesAndLadders.GamePlay.csproj" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.AgressivelyBad\ChutesAndLadders.Strategy.AgressivelyBad.csproj" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Genetic\ChutesAndLadders.Strategy.Genetic.csproj" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Greedy\ChutesAndLadders.Strategy.Greedy.csproj" />
    <ProjectReference Include="..\ChutesAndLadders.Strategy.Linear\ChutesAndLadders.Strategy.Linear.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\Greedy.razor">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>

</Project>
